name: Deploy Node.js Azure Http Trigger Function

on:
  push:
    branches: [ main ]  # Auslösen der Pipeline bei Änderungen auf dem main-Branch
    paths: 
      - 'backend/**'  # Nur bei Änderungen im backend-Verzeichnis

env:
  AZURE_FUNCTIONAPP_NAME: 'azurefunction2'  
  AZURE_FUNCTIONAPP_PACKAGE_PATH: 'backend'  
  NODE_VERSION: '14.x'  
  COSMOS_ENDPOINT: ${{ secrets.COSMOS_ENDPOINT }} 
  COSMOS_KEY: ${{ secrets.COSMOS_KEY }} 

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - name: 'Checkout Code'
      uses: actions/checkout@v3

    - name: 'Login to Azure via CLI'
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}  

    - name: 'Setup Node.js Environment'
      uses: actions/setup-node@v2
      with:
        node-version: ${{ env.NODE_VERSION }}  

    - name: 'Install Dependencies'
      run: |
        cd ${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}  
        npm install  # Abhängigkeiten installieren

    - name: 'Deploy Azure Function'
      uses: Azure/functions-action@v1
      with:
        app-name: ${{ env.AZURE_FUNCTIONAPP_NAME }}  
        package: '${{ env.AZURE_FUNCTIONAPP_PACKAGE_PATH }}'  
        publish-profile: ${{ secrets.AZURE_FUNCTIONAPP_PUBLISH_PROFILE }}

    - name: 'Logout from Azure'
      run: |
        az logout  # Abmelden von Azure
      if: always()  # Sicherstellen, dass Logout immer ausgeführt wird
